In [ ]:
#	Crear un objeto de tipo ndarray, con números enteros entre 64 hasta 1024.
import numpy as np
arreglo = np.arange(64 , 1025)
arreglo

array([  64,   65,   66,   67,   68,   69,   70,   71,   72,   73,   74,
         75,   76,   77,   78,   79,   80,   81,   82,   83,   84,   85,
         86,   87,   88,   89,   90,   91,   92,   93,   94,   95,   96,
         97,   98,   99,  100,  101,  102,  103,  104,  105,  106,  107,
        108,  109,  110,  111,  112,  113,  114,  115,  116,  117,  118,
        119,  120,  121,  122,  123,  124,  125,  126,  127,  128,  129,
        130,  131,  132,  133,  134,  135,  136,  137,  138,  139,  140,
        141,  142,  143,  144,  145,  146,  147,  148,  149,  150,  151,
        152,  153,  154,  155,  156,  157,  158,  159,  160,  161,  162,
        163,  164,  165,  166,  167,  168,  169,  170,  171,  172,  173,
        174,  175,  176,  177,  178,  179,  180,  181,  182,  183,  184,
        185,  186,  187,  188,  189,  190,  191,  192,  193,  194,  195,
        196,  197,  198,  199,  200,  201,  202,  203,  204,  205,  206,
        207,  208,  209,  210,  211,  212,  213,  2

In [ ]:
# Redimensionar a una matriz bidimensional que tenga las 1024 observaciones, pero que su dimensión tenga tanto el mismo número de filas como de columnas, con la finalidad de obtener una cuadrada.
arreglo = np.arange(64 , 1025).reshape((31,31))
arreglo

array([[  64,   65,   66,   67,   68,   69,   70,   71,   72,   73,   74,
          75,   76,   77,   78,   79,   80,   81,   82,   83,   84,   85,
          86,   87,   88,   89,   90,   91,   92,   93,   94],
       [  95,   96,   97,   98,   99,  100,  101,  102,  103,  104,  105,
         106,  107,  108,  109,  110,  111,  112,  113,  114,  115,  116,
         117,  118,  119,  120,  121,  122,  123,  124,  125],
       [ 126,  127,  128,  129,  130,  131,  132,  133,  134,  135,  136,
         137,  138,  139,  140,  141,  142,  143,  144,  145,  146,  147,
         148,  149,  150,  151,  152,  153,  154,  155,  156],
       [ 157,  158,  159,  160,  161,  162,  163,  164,  165,  166,  167,
         168,  169,  170,  171,  172,  173,  174,  175,  176,  177,  178,
         179,  180,  181,  182,  183,  184,  185,  186,  187],
       [ 188,  189,  190,  191,  192,  193,  194,  195,  196,  197,  198,
         199,  200,  201,  202,  203,  204,  205,  206,  207,  208,  209,
        

In [23]:
# crear columna de datos aleatorios de 30 observaciones

DatosAleatorios = np.random.randint(1,100,10)
Seleccion_datos=[]
for i in range(0,10,1):
  elegido = np.random.choice(DatosAleatorios)
  Seleccion_datos.append(elegido)

Seleccion = np.array(Seleccion_datos).reshape(10,1)
Seleccion



array([[61],
       [61],
       [28],
       [61],
       [16],
       [95],
       [83],
       [10],
       [61],
       [97]])

In [33]:
# creando cedulas con numeros aleatorios
Lista = ["Andres" , "Maria" , "Manuel" , "Daniel" , "Sarah" , "Cristian" , "Violetta" , "Lucia" , "Jackson" , "Jose"]
arreglo = np.array(Lista)
arreglo

cedulaAleatoria = np.random.randint(1000,9999,100)
cedulas=[]
for i in range(0,10,1):
  elegido = np.random.choice(cedulaAleatoria)
  cedulas.append(elegido)

cedulas


[7046, 5431, 9204, 6010, 3097, 6969, 3517, 8667, 7736, 4306]

In [34]:
# concatenar vector con las observaciones de nmbres y cedulas
np.ma.concatenate(([arreglo], [cedulas]), axis=0)

masked_array(
  data=[['Andres', 'Maria', 'Manuel', 'Daniel', 'Sarah', 'Cristian',
         'Violetta', 'Lucia', 'Jackson', 'Jose'],
        ['7046', '5431', '9204', '6010', '3097', '6969', '3517', '8667',
         '7736', '4306']],
  mask=False,
  fill_value='N/A',
  dtype='<U21')

In [35]:
# mostar del numero mas grande
np.amax(cedulas)

9204